apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app  # Server will look for this Labels !!!
    spec:
      containers:
        - name: my-container
          image: sargsyan/my-app:1.0
          # resources:
          #   limits:
          #     memory: 200Mi
          #   requests:
          #     cpu: 100m
          #     memory: 200Mi
          ports:
            - containerPort: 3000 # Conteineri meji port@ !

---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
spec:
  type: NodePort
  selector:
    app: my-app  # selecting PODs with labels
  ports:
    - port: 80 #load balanceri vra
      protocol: TCP
      targetPort: 3000 # port on POD
  type : LoadBalancer
      
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: my-deployment
# spec:
#   backend:
#     serviceName: my-app
#     servicePort: 80
